# The prefix that will appear right behind every message in the plugin
plugin_prefix: "&9&lBlock&b&lTower"

# The title of the chest inventory of the rooms GUI that will show up when the player
# uses the opengui command
gui_title: "&b&lRooms"

# Configs for rooms
open_room_item: "EMERALD"
open_room_item_lore:
  - "&e({current_players}/{total_slots})"
  - ""
  - "&bClick to join!"

full_room_item: "GOLD_INGOT"
full_room_item_lore:
  - "&e({current_players}/{total_slots})"
  - ""
  - "&cThis room is full"

resetting_room_item: "IRON_INGOT"
resetting_room_item_lore:
  - "&e({current_players}/{total_slots})"
  - ""
  - "&7This room is reseting..."

ongame_room_item: "REDSTONE"
ongame_room_item_lore:
  - "&e({current_players}/{total_slots})"
  - ""
  - "&cThis room is currently on game"

# Determines if the players will receive fall damage while playing
fall_damage_enabled: false